<<<<<<< HEAD
=======
"""Placeholder entry point generated by the uv project scaffold; the app runs via app.py."""


>>>>>>> 1d1e9f137cfd1123edbae5d8e955ce0b9c7fcf4a
def main():
    print("Hello from clinical-rag-with-ade!")


if __name__ == "__main__":
    main()
